import { defineObject, FieldType, OnDeleteAction, RelationType } from 'twenty-sdk/define';

import {
  CANDIDATE_STATUS_OPTIONS,
  CREATOR_TAG_OPTIONS,
  FIT_RATING_OPTIONS,
  ENGAGEMENT_QUALITY_OPTIONS,
} from 'src/constants/ugc-options';
import { UGC_FIELD_IDS, UGC_OBJECT_IDS } from 'src/constants/ugc-universal-identifiers';

export default defineObject({
  universalIdentifier: UGC_OBJECT_IDS.candidate,
  nameSingular: 'campaignCreatorCandidate',
  namePlural: 'campaignCreatorCandidates',
  labelSingular: 'Campaign Creator Candidate',
  labelPlural: 'Campaign Creator Candidates',
  description: 'Campaign-specific internal candidate record created when the Growth Team recommends a creator for review.',
  icon: 'IconUserPlus',
  labelIdentifierFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.candidate.creatorHandle,
  fields: [
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.creator,
      name: 'creator',
      label: 'Creator',
      type: FieldType.RELATION,
      icon: 'IconUserStar',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.creator,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creator.candidates,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'creatorId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.campaign,
      name: 'campaign',
      label: 'Campaign',
      type: FieldType.RELATION,
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.campaign,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.campaign.candidates,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'campaignId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.productRef,
      name: 'productRef',
      label: 'Product',
      type: FieldType.RELATION,
      icon: 'IconPackage',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.product,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.product.candidateRefs,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'productId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.creatorHandleLink,
      name: 'creatorHandleLink',
      label: 'Handle',
      type: FieldType.LINKS,
      icon: 'IconAt',
    },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.creatorHandle,
      name: 'creatorHandle',
      label: 'Handle (display)',
      type: FieldType.TEXT,
      icon: 'IconAt',
      description: 'Mirrors handle link label for kanban card titles.',
    },
    { universalIdentifier: UGC_FIELD_IDS.candidate.proposedBy, name: 'proposedBy', label: 'By', type: FieldType.TEXT, icon: 'IconUser' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.reason, name: 'reason', label: 'Reason', type: FieldType.TEXT, icon: 'IconBulb' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.source, name: 'source', label: 'Source', type: FieldType.TEXT, icon: 'IconInbox' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.dateProposed, name: 'dateProposed', label: 'Date Proposed', type: FieldType.DATE_TIME, icon: 'IconCalendarPlus' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.status, name: 'status', label: 'Status', type: FieldType.SELECT, icon: 'IconProgress', options: [...CANDIDATE_STATUS_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.candidate.decisionReason, name: 'decisionReason', label: 'Decision Reason', type: FieldType.TEXT, icon: 'IconNotes' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorNiche, name: 'creatorNiche', label: 'Niche', type: FieldType.TEXT, icon: 'IconCategory' },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.candidateTagList,
      name: 'candidateTagList',
      label: 'Tags',
      type: FieldType.MULTI_SELECT,
      icon: 'IconTags',
      options: [...CREATOR_TAG_OPTIONS],
    },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorCountry, name: 'creatorCountry', label: 'Country', type: FieldType.TEXT, icon: 'IconMapPin' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorLanguage, name: 'creatorLanguage', label: 'Language', type: FieldType.TEXT, icon: 'IconLanguage' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorFollowerCount, name: 'creatorFollowerCount', label: 'Follower Count', type: FieldType.NUMBER, icon: 'IconUsers' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorMedianViewsRecent, name: 'creatorMedianViewsRecent', label: 'Median Views (Recent)', type: FieldType.NUMBER, icon: 'IconEye' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorAvgViewsRecent, name: 'creatorAvgViewsRecent', label: 'Avg Views (Recent)', type: FieldType.NUMBER, icon: 'IconEye' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorEngagementRate, name: 'creatorEngagementRate', label: 'Engagement Rate', type: FieldType.NUMBER, icon: 'IconPercentage' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorAvgLikesRecent, name: 'creatorAvgLikesRecent', label: 'Avg Likes (Recent)', type: FieldType.NUMBER, icon: 'IconHeart' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorAvgCommentsRecent, name: 'creatorAvgCommentsRecent', label: 'Avg Comments (Recent)', type: FieldType.NUMBER, icon: 'IconMessage' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorPostsLast30Days, name: 'creatorPostsLast30Days', label: 'Posts Last 30 Days', type: FieldType.NUMBER, icon: 'IconCalendarStats' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorLastPostAt, name: 'creatorLastPostAt', label: 'Last Post At', type: FieldType.DATE_TIME, icon: 'IconCalendarTime', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorBrandFitRating, name: 'creatorBrandFitRating', label: 'Brand Fit', type: FieldType.RATING, icon: 'IconSparkles', options: [...FIT_RATING_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorAudienceFitRating, name: 'creatorAudienceFitRating', label: 'Audience Fit', type: FieldType.RATING, icon: 'IconUsersGroup', options: [...FIT_RATING_OPTIONS] },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.creatorEngagementQuality,
      name: 'creatorEngagementQuality',
      label: 'Engagement Quality',
      type: FieldType.SELECT,
      icon: 'IconChartBar',
      options: [...ENGAGEMENT_QUALITY_OPTIONS],
      isNullable: true,
    },
    { universalIdentifier: UGC_FIELD_IDS.candidate.creatorRiskNotes, name: 'creatorRiskNotes', label: 'Risk Notes', type: FieldType.TEXT, icon: 'IconAlertTriangle' },
    { universalIdentifier: UGC_FIELD_IDS.candidate.memberNotes, name: 'memberNotes', label: 'Notes', type: FieldType.TEXT, icon: 'IconNotes' },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.evaluations,
      name: 'evaluations',
      label: 'Evaluations',
      type: FieldType.RELATION,
      icon: 'IconChecklist',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.evaluation,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.evaluation.candidate,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.outreachRecords,
      name: 'outreachRecords',
      label: 'Outreach Records',
      type: FieldType.RELATION,
      icon: 'IconSend',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.outreach,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.outreach.candidate,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.candidate.messageDrafts,
      name: 'messageDrafts',
      label: 'Message Drafts',
      type: FieldType.RELATION,
      icon: 'IconMessage2',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.messageDraft,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageDraft.candidate,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
