import { defineObject, FieldType, OnDeleteAction, RelationType } from 'twenty-sdk/define';

import { PLATFORM_OPTIONS } from 'src/constants/ugc-options';
import { UGC_FIELD_IDS, UGC_OBJECT_IDS } from 'src/constants/ugc-universal-identifiers';

export default defineObject({
  universalIdentifier: UGC_OBJECT_IDS.campaign,
  nameSingular: 'campaign',
  namePlural: 'campaigns',
  labelSingular: 'Campaign',
  labelPlural: 'Campaigns',
  description: 'UGC campaign container for sourcing, outreach, content, goals, and reporting.',
  icon: 'IconTargetArrow',
  labelIdentifierFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.campaign.name,
  fields: [
    { universalIdentifier: UGC_FIELD_IDS.campaign.name, name: 'name', label: 'Name', type: FieldType.TEXT, icon: 'IconAbc' },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.budget,
      name: 'budget',
      label: 'Budget',
      type: FieldType.NUMBER,
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.budgetUsed,
      name: 'budgetUsed',
      label: 'Budget Used',
      type: FieldType.NUMBER,
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.budgetUsePercent,
      name: 'budgetUsePercent',
      label: 'Budget Use %',
      type: FieldType.NUMBER,
      icon: 'IconPercentage',
      isNullable: true,
      description: 'Auto-updated from budget and budget used.',
    },
    { universalIdentifier: UGC_FIELD_IDS.campaign.objective, name: 'objective', label: 'Objective', type: FieldType.TEXT, icon: 'IconTarget' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.product, name: 'product', label: 'Product', type: FieldType.TEXT, icon: 'IconPackage' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.targetAudience, name: 'targetAudience', label: 'Target Audience', type: FieldType.TEXT, icon: 'IconUsers' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.platforms, name: 'platforms', label: 'Platforms', type: FieldType.MULTI_SELECT, icon: 'IconDeviceMobile', options: [...PLATFORM_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.campaign.owner, name: 'owner', label: 'Owner', type: FieldType.TEXT, icon: 'IconUser' },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.status,
      name: 'status',
      label: 'Status',
      type: FieldType.SELECT,
      icon: 'IconProgress',
      options: [
        { value: 'PLANNING', label: 'Planning', position: 0, color: 'gray' },
        { value: 'ACTIVE', label: 'Active', position: 1, color: 'green' },
        { value: 'PAUSED', label: 'Paused', position: 2, color: 'orange' },
        { value: 'COMPLETED', label: 'Completed', position: 3, color: 'blue' },
        { value: 'ARCHIVED', label: 'Archived', position: 4, color: 'gray' },
      ],
    },
    { universalIdentifier: UGC_FIELD_IDS.campaign.startDate, name: 'startDate', label: 'Start Date', type: FieldType.DATE, icon: 'IconCalendar' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.endDate, name: 'endDate', label: 'End Date', type: FieldType.DATE, icon: 'IconCalendarDue' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.creatorSourcingGoal, name: 'creatorSourcingGoal', label: 'Creator Sourcing Goal', type: FieldType.NUMBER, icon: 'IconHash' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.contentSubmissionGoal, name: 'contentSubmissionGoal', label: 'Content Submission Goal', type: FieldType.NUMBER, icon: 'IconHash' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.performanceGoal, name: 'performanceGoal', label: 'Performance Goal', type: FieldType.TEXT, icon: 'IconChartBar' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.notes, name: 'notes', label: 'Notes', type: FieldType.TEXT, icon: 'IconNotes' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.weeklySummary, name: 'weeklySummary', label: 'Weekly Summary', type: FieldType.TEXT, icon: 'IconReport' },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.productRef,
      name: 'productRef',
      label: 'Product',
      type: FieldType.RELATION,
      icon: 'IconPackage',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.product,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.product.campaigns,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'productId' },
      isNullable: true,
    },
    { universalIdentifier: UGC_FIELD_IDS.campaign.briefDocumentLink, name: 'briefDocumentLink', label: 'Brief Document', type: FieldType.LINKS, icon: 'IconFileText' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.productDescription, name: 'productDescription', label: 'Product Description', type: FieldType.TEXT, icon: 'IconPackage' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.format, name: 'format', label: 'Format', type: FieldType.TEXT, icon: 'IconAspectRatio' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.deadline, name: 'deadline', label: 'Deadline', type: FieldType.DATE_TIME, icon: 'IconCalendarDue', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.campaign.submissionInstruction, name: 'submissionInstruction', label: 'Submission Instruction', type: FieldType.TEXT, icon: 'IconUpload' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.exampleHooks, name: 'exampleHooks', label: 'Example Hooks', type: FieldType.RICH_TEXT, icon: 'IconHook' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.doGuidelines, name: 'doGuidelines', label: 'Do Guidelines', type: FieldType.RICH_TEXT, icon: 'IconCircleCheck' },
    { universalIdentifier: UGC_FIELD_IDS.campaign.dontGuidelines, name: 'dontGuidelines', label: 'Do Not Guidelines', type: FieldType.RICH_TEXT, icon: 'IconCircleX' },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.candidates,
      name: 'candidates',
      label: 'Candidates',
      type: FieldType.RELATION,
      icon: 'IconUsersGroup',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.candidate,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.candidate.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.outreachRecords,
      name: 'outreachRecords',
      label: 'Outreach Records',
      type: FieldType.RELATION,
      icon: 'IconSend',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.outreach,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.outreach.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.briefs,
      name: 'briefs',
      label: 'Briefs',
      type: FieldType.RELATION,
      icon: 'IconClipboardText',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.brief,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.brief.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.deliverables,
      name: 'deliverables',
      label: 'Deliverables',
      type: FieldType.RELATION,
      icon: 'IconVideo',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.deliverable,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.deliverable.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.campaignMetrics,
      name: 'campaignMetrics',
      label: 'Campaign Metrics',
      type: FieldType.RELATION,
      icon: 'IconChartBar',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.campaignMetric,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.campaignMetric.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.creatorPerformanceMetrics,
      name: 'creatorPerformanceMetrics',
      label: 'Creator Performance Metrics',
      type: FieldType.RELATION,
      icon: 'IconChartLine',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.creatorPerformanceMetric,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creatorPerformanceMetric.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.messageThreads,
      name: 'messageThreads',
      label: 'Message Threads',
      type: FieldType.RELATION,
      icon: 'IconMessages',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.messageThread,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageThread.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.messageDrafts,
      name: 'messageDrafts',
      label: 'Message Drafts',
      type: FieldType.RELATION,
      icon: 'IconMessage2',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.messageDraft,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageDraft.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.contactWorkflows,
      name: 'contactWorkflows',
      label: 'Contact Workflows',
      type: FieldType.RELATION,
      icon: 'IconTimeline',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.contactWorkflow,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.contactWorkflow.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.campaign.scheduledContactTasks,
      name: 'scheduledContactTasks',
      label: 'Scheduled Contact Tasks',
      type: FieldType.RELATION,
      icon: 'IconClock',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.scheduledContactTask,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.scheduledContactTask.campaign,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
