import { defineObject, FieldType, RelationType } from 'twenty-sdk/define';

import {
  CANDIDATE_STATUS_OPTIONS,
  CREATOR_TAG_OPTIONS,
  FIT_RATING_OPTIONS,
  DELIVERABLE_REVIEW_STATUS_OPTIONS,
  ENGAGEMENT_QUALITY_OPTIONS,
  PIPELINE_STATUS_OPTIONS,
  PLATFORM_OPTIONS,
  REPLY_STATUS_OPTIONS,
} from 'src/constants/ugc-options';
import { UGC_FIELD_IDS, UGC_OBJECT_IDS } from 'src/constants/ugc-universal-identifiers';

export default defineObject({
  universalIdentifier: UGC_OBJECT_IDS.creator,
  nameSingular: 'creator',
  namePlural: 'creators',
  labelSingular: 'Creator',
  labelPlural: 'Creators',
  description: 'Canonical creator profile reused across campaigns.',
  icon: 'IconUserStar',
  labelIdentifierFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creator.name,
  fields: [
    { universalIdentifier: UGC_FIELD_IDS.creator.name, name: 'name', label: 'Name', type: FieldType.TEXT, icon: 'IconAbc' },
    { universalIdentifier: UGC_FIELD_IDS.creator.handle, name: 'handle', label: 'Handle', type: FieldType.TEXT, icon: 'IconAt' },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.price,
      name: 'price',
      label: 'Price',
      type: FieldType.NUMBER,
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    { universalIdentifier: UGC_FIELD_IDS.creator.platform, name: 'platform', label: 'Platform', type: FieldType.SELECT, icon: 'IconDeviceMobile', options: [...PLATFORM_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.creator.profileLink, name: 'profileLink', label: 'Profile Link', type: FieldType.LINKS, icon: 'IconLink' },
    { universalIdentifier: UGC_FIELD_IDS.creator.instagramLink, name: 'instagramLink', label: 'Instagram Link', type: FieldType.LINKS, icon: 'IconBrandInstagram' },
    { universalIdentifier: UGC_FIELD_IDS.creator.tiktokLink, name: 'tiktokLink', label: 'TikTok Link', type: FieldType.LINKS, icon: 'IconBrandTiktok' },
    { universalIdentifier: UGC_FIELD_IDS.creator.normalizedProfileLink, name: 'normalizedProfileLink', label: 'Normalized Profile Link', type: FieldType.TEXT, icon: 'IconLink' },
    { universalIdentifier: UGC_FIELD_IDS.creator.country, name: 'country', label: 'Country', type: FieldType.TEXT, icon: 'IconMapPin' },
    { universalIdentifier: UGC_FIELD_IDS.creator.language, name: 'language', label: 'Language', type: FieldType.TEXT, icon: 'IconLanguage' },
    { universalIdentifier: UGC_FIELD_IDS.creator.niche, name: 'niche', label: 'Niche', type: FieldType.TEXT, icon: 'IconCategory' },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.tagList,
      name: 'tagList',
      label: 'Tags',
      type: FieldType.MULTI_SELECT,
      icon: 'IconTags',
      options: [...CREATOR_TAG_OPTIONS],
    },
    { universalIdentifier: UGC_FIELD_IDS.creator.followerCount, name: 'followerCount', label: 'Follower Count', type: FieldType.NUMBER, icon: 'IconUsers' },
    { universalIdentifier: UGC_FIELD_IDS.creator.medianViewsRecent, name: 'medianViewsRecent', label: 'Median Views (Recent)', type: FieldType.NUMBER, icon: 'IconEye' },
    { universalIdentifier: UGC_FIELD_IDS.creator.avgViewsRecent, name: 'avgViewsRecent', label: 'Avg Views (Recent)', type: FieldType.NUMBER, icon: 'IconEye' },
    { universalIdentifier: UGC_FIELD_IDS.creator.engagementRate, name: 'engagementRate', label: 'Engagement Rate', type: FieldType.NUMBER, icon: 'IconPercentage' },
    { universalIdentifier: UGC_FIELD_IDS.creator.avgLikesRecent, name: 'avgLikesRecent', label: 'Avg Likes (Recent)', type: FieldType.NUMBER, icon: 'IconHeart' },
    { universalIdentifier: UGC_FIELD_IDS.creator.avgCommentsRecent, name: 'avgCommentsRecent', label: 'Avg Comments (Recent)', type: FieldType.NUMBER, icon: 'IconMessage' },
    { universalIdentifier: UGC_FIELD_IDS.creator.postsLast30Days, name: 'postsLast30Days', label: 'Posts Last 30 Days', type: FieldType.NUMBER, icon: 'IconCalendarStats' },
    { universalIdentifier: UGC_FIELD_IDS.creator.lastPostAt, name: 'lastPostAt', label: 'Last Post At', type: FieldType.DATE_TIME, icon: 'IconCalendarTime', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.creator.brandFitRating, name: 'brandFitRating', label: 'Brand Fit', type: FieldType.RATING, icon: 'IconSparkles', options: [...FIT_RATING_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.creator.audienceFitRating, name: 'audienceFitRating', label: 'Audience Fit', type: FieldType.RATING, icon: 'IconUsersGroup', options: [...FIT_RATING_OPTIONS] },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.engagementQuality,
      name: 'engagementQuality',
      label: 'Engagement Quality',
      type: FieldType.SELECT,
      icon: 'IconChartBar',
      options: [...ENGAGEMENT_QUALITY_OPTIONS],
    },
    { universalIdentifier: UGC_FIELD_IDS.creator.riskNotes, name: 'riskNotes', label: 'Risk Notes', type: FieldType.TEXT, icon: 'IconAlertTriangle' },
    { universalIdentifier: UGC_FIELD_IDS.creator.owner, name: 'owner', label: 'Owner', type: FieldType.TEXT, icon: 'IconUser' },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.reviewStatus,
      name: 'reviewStatus',
      label: 'Review Status',
      type: FieldType.SELECT,
      icon: 'IconClipboardCheck',
      options: [...CANDIDATE_STATUS_OPTIONS],
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.pipelineStatus,
      name: 'pipelineStatus',
      label: 'Pipeline Status',
      type: FieldType.SELECT,
      icon: 'IconProgress',
      options: [...PIPELINE_STATUS_OPTIONS],
      isNullable: true,
    },
    { universalIdentifier: UGC_FIELD_IDS.creator.activeCampaignName, name: 'activeCampaignName', label: 'Active Campaign', type: FieldType.TEXT, icon: 'IconTargetArrow' },
    { universalIdentifier: UGC_FIELD_IDS.creator.proposedReason, name: 'proposedReason', label: 'Proposed Reason', type: FieldType.TEXT, icon: 'IconBulb' },
    { universalIdentifier: UGC_FIELD_IDS.creator.nextFollowUpAt, name: 'nextFollowUpAt', label: 'Next Follow-Up At', type: FieldType.DATE_TIME, icon: 'IconBell', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.creator.lastContactedAt, name: 'lastContactedAt', label: 'Last Contacted At', type: FieldType.DATE_TIME, icon: 'IconCalendarTime', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.creator.firstContactedAt, name: 'firstContactedAt', label: 'First Contacted At', type: FieldType.DATE_TIME, icon: 'IconCalendarPlus', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.creator.outreachOwner, name: 'outreachOwner', label: 'By', type: FieldType.TEXT, icon: 'IconUser' },
    { universalIdentifier: UGC_FIELD_IDS.creator.blocker, name: 'blocker', label: 'Blocker', type: FieldType.TEXT, icon: 'IconAlertTriangle' },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.replyStatus,
      name: 'replyStatus',
      label: 'Reply Status',
      type: FieldType.SELECT,
      icon: 'IconMessageCircle',
      options: [...REPLY_STATUS_OPTIONS],
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.contentReviewStatus,
      name: 'contentReviewStatus',
      label: 'Content Review Status',
      type: FieldType.SELECT,
      icon: 'IconVideo',
      options: [...DELIVERABLE_REVIEW_STATUS_OPTIONS],
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.candidates,
      name: 'candidates',
      label: 'Campaign Candidates',
      type: FieldType.RELATION,
      icon: 'IconUsersGroup',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.candidate,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.candidate.creator,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.outreachRecords,
      name: 'outreachRecords',
      label: 'Outreach Records',
      type: FieldType.RELATION,
      icon: 'IconSend',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.outreach,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.outreach.creator,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.deliverables,
      name: 'deliverables',
      label: 'Deliverables',
      type: FieldType.RELATION,
      icon: 'IconVideo',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.deliverable,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.deliverable.creator,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.creatorPerformanceMetrics,
      name: 'creatorPerformanceMetrics',
      label: 'Creator Performance Metrics',
      type: FieldType.RELATION,
      icon: 'IconChartLine',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.creatorPerformanceMetric,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creatorPerformanceMetric.creator,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.messageThreads,
      name: 'messageThreads',
      label: 'Message Threads',
      type: FieldType.RELATION,
      icon: 'IconMessages',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.messageThread,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageThread.creator,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.messageDrafts,
      name: 'messageDrafts',
      label: 'Message Drafts',
      type: FieldType.RELATION,
      icon: 'IconMessage2',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.messageDraft,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageDraft.creator,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.creator.scheduledContactTasks,
      name: 'scheduledContactTasks',
      label: 'Scheduled Contact Tasks',
      type: FieldType.RELATION,
      icon: 'IconClock',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.scheduledContactTask,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.scheduledContactTask.creator,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
