import { defineObject, FieldType, OnDeleteAction, RelationType } from 'twenty-sdk/define';

import { DELIVERABLE_REVIEW_STATUS_OPTIONS } from 'src/constants/ugc-options';
import { UGC_FIELD_IDS, UGC_OBJECT_IDS } from 'src/constants/ugc-universal-identifiers';

export default defineObject({
  universalIdentifier: UGC_OBJECT_IDS.deliverable,
  nameSingular: 'deliverable',
  namePlural: 'deliverables',
  labelSingular: 'Deliverable',
  labelPlural: 'Deliverables',
  description: 'Creator content submission, review, and approved asset tracking.',
  icon: 'IconVideo',
  labelIdentifierFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.deliverable.creatorHandle,
  fields: [
    {
      universalIdentifier: UGC_FIELD_IDS.deliverable.creatorHandleLink,
      name: 'creatorHandleLink',
      label: 'Handle',
      type: FieldType.LINKS,
      icon: 'IconAt',
    },
    {
      universalIdentifier: UGC_FIELD_IDS.deliverable.creatorHandle,
      name: 'creatorHandle',
      label: 'Handle (display)',
      type: FieldType.TEXT,
      icon: 'IconAt',
      description: 'Mirrors handle link label for kanban card titles.',
    },
    {
      universalIdentifier: UGC_FIELD_IDS.deliverable.creator,
      name: 'creator',
      label: 'Creator',
      type: FieldType.RELATION,
      icon: 'IconUserStar',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.creator,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creator.deliverables,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'creatorId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.deliverable.campaign,
      name: 'campaign',
      label: 'Campaign',
      type: FieldType.RELATION,
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.campaign,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.campaign.deliverables,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'campaignId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.deliverable.productRef,
      name: 'productRef',
      label: 'Product',
      type: FieldType.RELATION,
      icon: 'IconPackage',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.product,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.product.deliverableRefs,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'productId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.deliverable.brief,
      name: 'brief',
      label: 'Brief',
      type: FieldType.RELATION,
      icon: 'IconClipboardText',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.brief,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.brief.deliverables,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'briefId' },
      isNullable: true,
    },
    { universalIdentifier: UGC_FIELD_IDS.deliverable.submissionLink, name: 'submissionLink', label: 'Submission Link', type: FieldType.LINKS, icon: 'IconLink' },
    { universalIdentifier: UGC_FIELD_IDS.deliverable.submittedAt, name: 'submittedAt', label: 'Submitted At', type: FieldType.DATE_TIME, icon: 'IconCalendarPlus', isNullable: true },
    {
      universalIdentifier: UGC_FIELD_IDS.deliverable.reviewStatus,
      name: 'reviewStatus',
      label: 'Review Status',
      type: FieldType.SELECT,
      icon: 'IconChecklist',
      options: [...DELIVERABLE_REVIEW_STATUS_OPTIONS],
    },
    { universalIdentifier: UGC_FIELD_IDS.deliverable.reviewer, name: 'reviewer', label: 'Reviewer', type: FieldType.TEXT, icon: 'IconUserCheck' },
    { universalIdentifier: UGC_FIELD_IDS.deliverable.revisionNotes, name: 'revisionNotes', label: 'Revision Notes', type: FieldType.TEXT, icon: 'IconNotes' },
    { universalIdentifier: UGC_FIELD_IDS.deliverable.approvedAssetLink, name: 'approvedAssetLink', label: 'Approved Asset Link', type: FieldType.LINKS, icon: 'IconLink' },
    {
      universalIdentifier: UGC_FIELD_IDS.deliverable.performanceMetrics,
      name: 'performanceMetrics',
      label: 'Performance Metrics',
      type: FieldType.RELATION,
      icon: 'IconChartBar',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.creatorPerformanceMetric,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creatorPerformanceMetric.deliverable,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
