import { defineObject, FieldType, OnDeleteAction, RelationType } from 'twenty-sdk/define';

import { CHANNEL_OPTIONS, DRAFT_STATUS_OPTIONS } from 'src/constants/ugc-options';
import { UGC_FIELD_IDS, UGC_OBJECT_IDS } from 'src/constants/ugc-universal-identifiers';

export default defineObject({
  universalIdentifier: UGC_OBJECT_IDS.messageDraft,
  nameSingular: 'messageDraft',
  namePlural: 'messageDrafts',
  labelSingular: 'Message Draft',
  labelPlural: 'Message Drafts',
  description: 'Draft email, Instagram DM, or TikTok DM prepared for human review and manual send.',
  icon: 'IconMessagePlus',
  labelIdentifierFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageDraft.subject,
  fields: [
    {
      universalIdentifier: UGC_FIELD_IDS.messageDraft.creator,
      name: 'creator',
      label: 'Creator',
      type: FieldType.RELATION,
      icon: 'IconUserStar',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.creator,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creator.messageDrafts,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'creatorId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.messageDraft.campaign,
      name: 'campaign',
      label: 'Campaign',
      type: FieldType.RELATION,
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.campaign,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.campaign.messageDrafts,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'campaignId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.messageDraft.candidate,
      name: 'candidate',
      label: 'Candidate',
      type: FieldType.RELATION,
      icon: 'IconUserPlus',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.candidate,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.candidate.messageDrafts,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'candidateId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.messageDraft.outreachRecord,
      name: 'outreachRecord',
      label: 'Outreach Record',
      type: FieldType.RELATION,
      icon: 'IconSend',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.outreach,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.outreach.messageDrafts,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'outreachRecordId' },
      isNullable: true,
    },
    { universalIdentifier: UGC_FIELD_IDS.messageDraft.channel, name: 'channel', label: 'Channel', type: FieldType.SELECT, icon: 'IconMessage', options: [...CHANNEL_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.messageDraft.subject, name: 'subject', label: 'Subject', type: FieldType.TEXT, icon: 'IconAbc' },
    { universalIdentifier: UGC_FIELD_IDS.messageDraft.body, name: 'body', label: 'Body', type: FieldType.TEXT, icon: 'IconTextCaption' },
    { universalIdentifier: UGC_FIELD_IDS.messageDraft.status, name: 'status', label: 'Status', type: FieldType.SELECT, icon: 'IconProgress', options: [...DRAFT_STATUS_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.messageDraft.scheduledFor, name: 'scheduledFor', label: 'Scheduled For', type: FieldType.DATE_TIME, icon: 'IconCalendarTime', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.messageDraft.approvedBy, name: 'approvedBy', label: 'Approved By', type: FieldType.TEXT, icon: 'IconUserCheck' },
    { universalIdentifier: UGC_FIELD_IDS.messageDraft.sentManuallyAt, name: 'sentManuallyAt', label: 'Sent Manually At', type: FieldType.DATE_TIME, icon: 'IconSend', isNullable: true },
    {
      universalIdentifier: UGC_FIELD_IDS.messageDraft.scheduledTasks,
      name: 'scheduledTasks',
      label: 'Scheduled Tasks',
      type: FieldType.RELATION,
      icon: 'IconClock',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.scheduledContactTask,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.scheduledContactTask.messageDraft,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});

