import { defineObject, FieldType, OnDeleteAction, RelationType } from 'twenty-sdk/define';

import { CHANNEL_OPTIONS, PIPELINE_STATUS_OPTIONS, REPLY_STATUS_OPTIONS } from 'src/constants/ugc-options';
import { UGC_FIELD_IDS, UGC_OBJECT_IDS } from 'src/constants/ugc-universal-identifiers';

export default defineObject({
  universalIdentifier: UGC_OBJECT_IDS.outreach,
  nameSingular: 'outreachRecord',
  namePlural: 'outreachRecords',
  labelSingular: 'Outreach Record',
  labelPlural: 'Outreach Records',
  description: 'Contact, reply, follow-up, and pipeline tracking for campaign creators.',
  icon: 'IconSend',
  labelIdentifierFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.outreach.creatorHandle,
  fields: [
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.creatorHandleLink,
      name: 'creatorHandleLink',
      label: 'Handle',
      type: FieldType.LINKS,
      icon: 'IconAt',
    },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.creatorHandle,
      name: 'creatorHandle',
      label: 'Handle (display)',
      type: FieldType.TEXT,
      icon: 'IconAt',
      description: 'Mirrors handle link label for kanban card titles.',
    },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.creatorPrice,
      name: 'creatorPrice',
      label: 'Price',
      type: FieldType.NUMBER,
      icon: 'IconCurrencyDollar',
      isNullable: true,
      description: 'Copied from creator price for operations kanban.',
    },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.creator,
      name: 'creator',
      label: 'Creator',
      type: FieldType.RELATION,
      icon: 'IconUserStar',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.creator,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creator.outreachRecords,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'creatorId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.campaign,
      name: 'campaign',
      label: 'Campaign',
      type: FieldType.RELATION,
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.campaign,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.campaign.outreachRecords,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'campaignId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.productRef,
      name: 'productRef',
      label: 'Product',
      type: FieldType.RELATION,
      icon: 'IconPackage',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.product,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.product.outreachRefs,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'productId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.candidate,
      name: 'candidate',
      label: 'Candidate',
      type: FieldType.RELATION,
      icon: 'IconUserPlus',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.candidate,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.candidate.outreachRecords,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'candidateId' },
      isNullable: true,
    },
    { universalIdentifier: UGC_FIELD_IDS.outreach.member, name: 'member', label: 'Member', type: FieldType.TEXT, icon: 'IconUser' },
    { universalIdentifier: UGC_FIELD_IDS.outreach.contactMethod, name: 'contactMethod', label: 'Contact Method', type: FieldType.SELECT, icon: 'IconMessage', options: [...CHANNEL_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.outreach.firstContactedAt, name: 'firstContactedAt', label: 'First Contacted At', type: FieldType.DATE_TIME, icon: 'IconCalendarPlus', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.outreach.lastContactedAt, name: 'lastContactedAt', label: 'Last Contacted At', type: FieldType.DATE_TIME, icon: 'IconCalendarTime', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.outreach.nextFollowUpAt, name: 'nextFollowUpAt', label: 'Next Follow-Up At', type: FieldType.DATE_TIME, icon: 'IconBell', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.outreach.brief, name: 'brief', label: 'Brief', type: FieldType.LINKS, icon: 'IconClipboardText', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.outreach.contract, name: 'contract', label: 'Contract', type: FieldType.LINKS, icon: 'IconFileDescription', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.outreach.submitted, name: 'submitted', label: 'Submitted', type: FieldType.LINKS, icon: 'IconLink', isNullable: true },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.replyStatus,
      name: 'replyStatus',
      label: 'Reply Status',
      type: FieldType.SELECT,
      icon: 'IconMessageCircle',
      options: [...REPLY_STATUS_OPTIONS],
    },
    { universalIdentifier: UGC_FIELD_IDS.outreach.pipelineStatus, name: 'pipelineStatus', label: 'Pipeline Status', type: FieldType.SELECT, icon: 'IconProgress', options: [...PIPELINE_STATUS_OPTIONS] },
    { universalIdentifier: UGC_FIELD_IDS.outreach.blocker, name: 'blocker', label: 'Blocker', type: FieldType.TEXT, icon: 'IconAlertTriangle' },
    { universalIdentifier: UGC_FIELD_IDS.outreach.notes, name: 'notes', label: 'Notes', type: FieldType.TEXT, icon: 'IconNotes' },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.messageThreads,
      name: 'messageThreads',
      label: 'Message Threads',
      type: FieldType.RELATION,
      icon: 'IconMessages',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.messageThread,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageThread.outreachRecord,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.messageDrafts,
      name: 'messageDrafts',
      label: 'Message Drafts',
      type: FieldType.RELATION,
      icon: 'IconMessage2',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.messageDraft,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageDraft.outreachRecord,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: UGC_FIELD_IDS.outreach.scheduledContactTasks,
      name: 'scheduledContactTasks',
      label: 'Scheduled Contact Tasks',
      type: FieldType.RELATION,
      icon: 'IconClock',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.scheduledContactTask,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.scheduledContactTask.outreachRecord,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
