import { defineObject, FieldType, OnDeleteAction, RelationType } from 'twenty-sdk/define';

import { TASK_STATUS_OPTIONS } from 'src/constants/ugc-options';
import { UGC_FIELD_IDS, UGC_OBJECT_IDS } from 'src/constants/ugc-universal-identifiers';

export default defineObject({
  universalIdentifier: UGC_OBJECT_IDS.scheduledContactTask,
  nameSingular: 'scheduledContactTask',
  namePlural: 'scheduledContactTasks',
  labelSingular: 'Scheduled Contact Task',
  labelPlural: 'Scheduled Contact Tasks',
  description: 'Scheduled draft-generation task for one creator.',
  icon: 'IconClock',
  fields: [
    {
      universalIdentifier: UGC_FIELD_IDS.scheduledContactTask.workflow,
      name: 'workflow',
      label: 'Workflow',
      type: FieldType.RELATION,
      icon: 'IconTimeline',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.contactWorkflow,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.contactWorkflow.scheduledTasks,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'workflowId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.scheduledContactTask.workflowStep,
      name: 'workflowStep',
      label: 'Workflow Step',
      type: FieldType.RELATION,
      icon: 'IconListNumbers',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.contactWorkflowStep,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.contactWorkflowStep.scheduledTasks,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'workflowStepId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.scheduledContactTask.creator,
      name: 'creator',
      label: 'Creator',
      type: FieldType.RELATION,
      icon: 'IconUserStar',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.creator,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.creator.scheduledContactTasks,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'creatorId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.scheduledContactTask.campaign,
      name: 'campaign',
      label: 'Campaign',
      type: FieldType.RELATION,
      icon: 'IconTargetArrow',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.campaign,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.campaign.scheduledContactTasks,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'campaignId' },
      isNullable: true,
    },
    {
      universalIdentifier: UGC_FIELD_IDS.scheduledContactTask.outreachRecord,
      name: 'outreachRecord',
      label: 'Outreach Record',
      type: FieldType.RELATION,
      icon: 'IconSend',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.outreach,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.outreach.scheduledContactTasks,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'outreachRecordId' },
      isNullable: true,
    },
    { universalIdentifier: UGC_FIELD_IDS.scheduledContactTask.scheduledFor, name: 'scheduledFor', label: 'Scheduled For', type: FieldType.DATE_TIME, icon: 'IconCalendarTime', isNullable: true },
    { universalIdentifier: UGC_FIELD_IDS.scheduledContactTask.status, name: 'status', label: 'Status', type: FieldType.SELECT, icon: 'IconProgress', options: [...TASK_STATUS_OPTIONS] },
    {
      universalIdentifier: UGC_FIELD_IDS.scheduledContactTask.messageDraft,
      name: 'messageDraft',
      label: 'Message Draft',
      type: FieldType.RELATION,
      icon: 'IconMessagePlus',
      relationTargetObjectMetadataUniversalIdentifier: UGC_OBJECT_IDS.messageDraft,
      relationTargetFieldMetadataUniversalIdentifier: UGC_FIELD_IDS.messageDraft.scheduledTasks,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'messageDraftId' },
      isNullable: true,
    },
  ],
});
